/* =============================================================================
   Science Claw — SAMPLE QUESTION LIBRARY   (window.SCIENCE_QUESTION_BANK)
   -----------------------------------------------------------------------------
   34 original P3–P6 practice questions, each fully worked with CECL
   (Choice · Evidence · Concept · Link), keyword chain and "do not accept" list.
   Mapped to the MOE Primary Science syllabus themes.

   WHY IT EXISTS: these ship WITH the app so a student can be coached through a
   real question even with NO internet (the live-AI reader needs a connection;
   this library never does). The Shirtpapa Genie turns any entry below into the
   same step-by-step CECL coaching flow — prompts, lenient marking, a twin, and
   a downloadable summary — entirely offline.

   SCHEMA (per entry):
     id        stable id
     level     'P3' | 'P4' | 'P5' | 'P6'
     topic     short topic name
     theme     'Diversity' | 'Cycles' | 'Systems' | 'Interactions' | 'Energy'
     marks     mark allocation
     lo        the learning outcome it tests
     question  the question stem (+ any "Explain" ask)
     table     [{label, value}]            (optional — rendered as data/bar chart)
     diagram   {type:'chain',nodes:[…]}    (optional — food chain etc.)
               {type:'circuit',components:[…],note}  (optional — circuit schematic)
     choice / evidence / concept / link   the model CECL answer (house-style)
     keywords  the keyword chain a marker looks for
     dna       "do not accept" — common wrong answers
   ========================================================================== */
(function () {
  var BANK = [
    /* ---------------- P3 ---------------- */
    {
      id: 'p3-living', level: 'P3', topic: 'Living & Non-living Things', theme: 'Diversity', marks: 2,
      lo: 'Describe the characteristics of living things (need water, food, air; grow, respond, reproduce).',
      question: 'A toy robot dog can move, make sounds and flash its eyes when its batteries are switched on. Explain why scientists still classify the robot dog as a non-living thing.',
      choice: 'The robot dog is a non-living thing.',
      evidence: 'It only moves and makes sounds using batteries (an external power source).',
      concept: 'Living things grow, respond and reproduce on their own, and need food, water and air to survive.',
      link: 'Because the robot cannot grow, reproduce or produce young on its own, it is non-living.',
      keywords: ['grow', 'reproduce', 'non-living'],
      dna: ['it is made of metal/plastic', 'it cannot talk'],
      twin: {
        stem: 'A battery-powered toy car can move forward and flash its lights when it is switched on.',
        ask: 'Explain why scientists still classify the toy car as a non-living thing.',
        choice: 'The toy car is a non-living thing.',
        evidence: 'It only moves and lights up using a battery (an external power source).',
        concept: 'Living things grow, respond and reproduce on their own, and need food, water and air.',
        link: 'Because the toy car cannot grow, reproduce or produce young on its own, it is non-living.',
        keywords: ['grow', 'reproduce', 'non-living'],
      },
    },
    {
      id: 'p3-classify', level: 'P3', topic: 'Classifying Animals', theme: 'Diversity', marks: 2,
      lo: 'Recognise broad groups of animals based on similarities and differences.',
      question: 'The table shows some features of animal P. Which group of animals does animal P belong to? Explain using the features given.',
      table: [{ label: 'Body covering', value: 'Dry scales' }, { label: 'Where it lays eggs', value: 'On land' }, { label: 'How it breathes', value: 'With lungs' }],
      choice: 'Animal P is a reptile.',
      evidence: 'It has dry scales and lays its eggs on land.',
      concept: 'Reptiles have dry, scaly skin and lay their eggs on land.',
      link: 'Since animal P has dry scales and lays eggs on land, it belongs to the reptile group.',
      keywords: ['reptile', 'dry scales', 'lay eggs on land'],
      dna: ['it is an amphibian (amphibians have moist skin)', 'because it has lungs only'],
      twin: {
        stem: 'The table shows features of animal Q: its body is covered with feathers, it has a beak, and it lays eggs with hard shells.',
        ask: 'Which group of animals does animal Q belong to? Explain using the features given.',
        choice: 'Animal Q is a bird.',
        evidence: 'It is covered with feathers and has a beak.',
        concept: 'Birds have feathers and beaks, and lay eggs with hard shells.',
        link: 'Since animal Q has feathers and a beak, it belongs to the bird group.',
        keywords: ['bird', 'feathers', 'beak'],
      },
    },
    {
      id: 'p3-raincoat', level: 'P3', topic: 'Properties of Materials', theme: 'Diversity', marks: 2,
      lo: 'Relate the use of materials to their physical properties (waterproof).',
      question: 'The table shows how much water four materials absorbed. Which material is most suitable for making a raincoat? Explain your choice.',
      table: [{ label: 'Material W', value: '0 ml absorbed' }, { label: 'Material X', value: '8 ml absorbed' }, { label: 'Material Y', value: '3 ml absorbed' }, { label: 'Material Z', value: '12 ml absorbed' }],
      choice: 'Material W is most suitable for a raincoat.',
      evidence: 'Material W absorbed no water (0 ml), the least of all four.',
      concept: 'A waterproof material does not absorb water, keeping the wearer dry.',
      link: 'Because material W does not absorb water, it is waterproof and best for a raincoat.',
      keywords: ['waterproof', 'does not absorb water'],
      dna: ['material W is strong', 'because it is light'],
    },
    {
      id: 'p3-glass', level: 'P3', topic: 'Properties of Materials', theme: 'Diversity', marks: 2,
      lo: 'Relate the use of materials to their physical properties (transparency).',
      question: 'The windows of a classroom are made of glass. Explain why glass is a suitable material for a window.',
      choice: 'Glass is a suitable material for a window.',
      evidence: 'Glass is transparent.',
      concept: 'Transparent materials allow most light to pass through them.',
      link: 'Because glass lets light pass through, sunlight can enter the classroom and people can see through the window.',
      keywords: ['transparent', 'allow light to pass through'],
      dna: ['glass is hard', 'glass is smooth'],
    },
    {
      id: 'p3-butterfly', level: 'P3', topic: 'Life Cycles', theme: 'Cycles', marks: 2,
      lo: 'Show an understanding that different living things have different life cycles and stages.',
      question: "A vegetable farmer notices butterflies near his crops. At which stage of the butterfly's life cycle is his crop most likely to be damaged? Explain your answer.",
      choice: 'The crop is most likely damaged at the larva (caterpillar) stage.',
      evidence: 'It is the caterpillar that is found feeding on the leaves.',
      concept: 'During the larva stage, the caterpillar feeds on leaves to grow.',
      link: 'Because the caterpillar eats leaves to grow, the larva stage causes the most damage to the crop.',
      keywords: ['larva', 'caterpillar', 'feeds on leaves'],
      dna: ['the adult/butterfly stage', 'the pupa stage'],
    },
    {
      id: 'p3-pupa', level: 'P3', topic: 'Life Cycles', theme: 'Cycles', marks: 2,
      lo: 'Compare the life cycles of different animals.',
      question: 'The table shows the number of stages in the life cycles of two insects. Which insect does NOT have a pupa stage? Explain using the table.',
      table: [{ label: 'Insect J', value: '4 stages: egg → larva → pupa → adult' }, { label: 'Insect K', value: '3 stages: egg → young → adult' }],
      choice: 'Insect K does not have a pupa stage.',
      evidence: "Insect K's life cycle has only 3 stages: egg, young and adult.",
      concept: 'A life cycle with a pupa stage has four stages, while one without a pupa has three.',
      link: 'Since insect K has only three stages and no pupa is listed, it does not have a pupa stage.',
      keywords: ['pupa', 'three stages'],
      dna: ['insect J', 'both insects have a pupa'],
    },
    {
      id: 'p3-repel', level: 'P3', topic: 'Magnets', theme: 'Interactions', marks: 2,
      lo: 'Show that like poles of magnets repel and unlike poles attract.',
      question: 'When Meiling brings the ends of two bar magnets close together, the magnets push away from each other. What can she conclude about the two ends? Explain.',
      choice: 'The two ends are like (same) poles.',
      evidence: 'The two magnets pushed away from / repelled each other.',
      concept: 'Like poles of magnets repel each other, while unlike poles attract.',
      link: 'Because the two ends repelled each other, they must be like poles.',
      keywords: ['like poles', 'repel'],
      dna: ['unlike poles', 'they attract'],
    },
    {
      id: 'p3-magnetic', level: 'P3', topic: 'Magnets', theme: 'Interactions', marks: 2,
      lo: 'Identify magnetic and non-magnetic materials.',
      question: 'The table shows what happened when a magnet was brought near four objects. Which object is made of a magnetic material? Explain.',
      table: [{ label: 'Object 1 (eraser)', value: 'Not attracted' }, { label: 'Object 2 (steel paperclip)', value: 'Attracted' }, { label: 'Object 3 (plastic ruler)', value: 'Not attracted' }, { label: 'Object 4 (wooden block)', value: 'Not attracted' }],
      choice: 'Object 2, the steel paperclip, is made of a magnetic material.',
      evidence: 'Only the steel paperclip was attracted to the magnet.',
      concept: 'Magnetic materials, such as iron and steel, are attracted to magnets.',
      link: 'Because the steel paperclip was attracted to the magnet, it is made of a magnetic material.',
      keywords: ['magnetic material', 'attracted to the magnet'],
      dna: ['object 2 is metal (not all metals are magnetic)', 'it is heavy'],
    },
    /* ---------------- P4 ---------------- */
    {
      id: 'p4-roots', level: 'P4', topic: 'Plant Parts & Functions', theme: 'Systems', marks: 2,
      lo: 'State the functions of plant parts (roots absorb water and mineral salts).',
      question: 'Insects in the soil damaged most of the roots of a young plant. Explain how this damage would affect the plant.',
      choice: 'The plant would wilt and not grow well.',
      evidence: "Most of the plant's roots were damaged.",
      concept: 'Roots absorb water and mineral salts from the soil for the plant.',
      link: 'With fewer working roots, less water and mineral salts are absorbed, so the plant wilts and grows poorly.',
      keywords: ['roots', 'absorb water and mineral salts'],
      dna: ['the plant cannot make food (that is the leaves)', 'roots make food'],
    },
    {
      id: 'p4-stem', level: 'P4', topic: 'Plant Parts & Functions', theme: 'Systems', marks: 2,
      lo: 'State the function of the stem (transports water from roots to leaves).',
      question: 'A white flower with a cut stem is placed in a beaker of red-coloured water. After a few hours, the petals turn red. Explain this observation.',
      choice: 'The petals turned red because the coloured water travelled up to them.',
      evidence: 'The red-coloured water was taken in through the cut stem.',
      concept: 'The stem contains water-carrying tubes that transport water from the roots up to the leaves and flowers.',
      link: 'The coloured water moved up the water-carrying tubes in the stem to the petals, turning them red.',
      keywords: ['stem', 'water-carrying tubes', 'transport water'],
      dna: ['the flower drank the water', 'the petals absorbed it directly'],
    },
    {
      id: 'p4-minced', level: 'P4', topic: 'Digestive System', theme: 'Systems', marks: 2,
      lo: 'Recognise the role of physical digestion (breaking food into smaller pieces).',
      question: 'At a cooking demonstration, a chef minces (cuts into very small pieces) some meat before cooking porridge for a baby. Explain why the minced meat is easier for the baby to digest than one large chunk of meat.',
      choice: 'The minced meat is easier and faster for the baby to digest.',
      evidence: 'The meat has been minced into very small pieces.',
      concept: 'Smaller pieces have a larger total surface area, so more food can be in contact with digestive juices.',
      link: 'With more surface in contact with digestive juices, the minced meat is broken down and digested faster.',
      keywords: ['surface area', 'digestive juices', 'faster digestion'],
      dna: ['smaller so easier (no concept)', 'minced meat has more nutrients'],
    },
    {
      id: 'p4-intestine', level: 'P4', topic: 'Digestive System', theme: 'Systems', marks: 2,
      lo: 'State the function of the small intestine (absorbs digested food).',
      question: "A patient's small intestine is not able to work properly. Explain how this would affect the amount of energy the patient's body can get from food.",
      choice: "The patient's body would get less energy from food.",
      evidence: "The patient's small intestine is not working properly.",
      concept: 'The small intestine absorbs digested food into the blood to be carried to the body.',
      link: 'With less digested food absorbed into the blood, less is delivered to the body, so the body gets less energy.',
      keywords: ['small intestine', 'absorbs digested food', 'blood'],
      dna: ['food cannot be chewed', 'the stomach stops working'],
    },
    {
      id: 'p4-mass', level: 'P4', topic: 'Matter & States of Water', theme: 'Cycles', marks: 2,
      lo: 'Understand that mass does not change with a change in state.',
      question: 'An ice cube of mass 20 g is left on a table until it completely melts into water. Will the mass of the water be more than, less than, or the same as 20 g? Explain.',
      choice: 'The mass of the water will be the same, 20 g.',
      evidence: 'The ice only melted from a solid into a liquid.',
      concept: 'A change in state does not add or remove any matter, so the mass stays the same.',
      link: 'As only the state changed from solid to liquid, no matter was gained or lost, so the mass remains 20 g.',
      keywords: ['change of state', 'mass stays the same'],
      dna: ['mass decreases because it melted', 'water is lighter than ice'],
    },
    {
      id: 'p4-puddle', level: 'P4', topic: 'Matter & States of Water', theme: 'Cycles', marks: 2,
      lo: 'Show an understanding of evaporation.',
      question: 'After a rain shower, a puddle of water on the road slowly disappears on a hot, sunny afternoon. Name and explain the process that caused the puddle to disappear.',
      choice: 'The process is evaporation.',
      evidence: 'The puddle disappeared on a hot, sunny afternoon.',
      concept: 'When water gains heat, it changes from a liquid into water vapour (evaporation).',
      link: 'The water in the puddle gained heat from the sun and evaporated into water vapour, so the puddle disappeared.',
      keywords: ['evaporation', 'gains heat', 'water vapour'],
      dna: ['the water soaked into the road only', 'condensation'],
    },
    {
      id: 'p4-shadow', level: 'P4', topic: 'Light & Shadows', theme: 'Energy', marks: 2,
      lo: 'Investigate how the size of a shadow changes with distance from the light source.',
      question: 'The table shows the size of a shadow as an object is moved towards a torch. Describe and explain how the shadow size changes as the object moves closer to the torch.',
      table: [{ label: 'Object 30 cm from torch', value: 'Shadow 8 cm' }, { label: 'Object 20 cm from torch', value: 'Shadow 12 cm' }, { label: 'Object 10 cm from torch', value: 'Shadow 20 cm' }],
      evidence: 'The shadow grew from 8 cm to 20 cm as the object moved from 30 cm to 10 cm from the torch.',
      concept: 'When an object is closer to the light source, it blocks more light, forming a larger shadow.',
      link: 'Thus, as the object moves closer to the torch, the shadow becomes larger.',
      keywords: ['blocks more light', 'larger shadow'],
      dna: ['the shadow gets smaller', 'the torch gets brighter'],
      twin: {
        stem: 'A torch shines on a ball. As the ball is moved away from the torch, the shadow is measured: 10 cm away → 18 cm shadow, 20 cm away → 11 cm shadow, 30 cm away → 7 cm shadow.',
        ask: 'Describe and explain how the shadow size changes as the ball moves away from the torch.',
        evidence: 'The shadow shrank from 18 cm to 7 cm as the ball moved from 10 cm to 30 cm away.',
        concept: 'An object further from the light source blocks less light, forming a smaller shadow.',
        link: 'Thus, as the ball moves away from the torch, the shadow becomes smaller.',
        keywords: ['blocks less light', 'smaller shadow'],
      },
    },
    {
      id: 'p4-darkroom', level: 'P4', topic: 'Light & Shadows', theme: 'Energy', marks: 2,
      lo: 'Recognise that we see an object when light from it enters our eyes.',
      question: 'Inside a completely dark room with no light at all, Aiman cannot see the table in front of him. Explain why he cannot see the table.',
      choice: 'Aiman cannot see the table.',
      evidence: 'There is no light at all in the room.',
      concept: 'We can see an object only when light from it enters our eyes.',
      link: "With no light to be reflected off the table into Aiman's eyes, he cannot see the table.",
      keywords: ['light enters our eyes', 'reflect light'],
      dna: ['the table is black', 'his eyes are closed'],
    },
    {
      id: 'p4-cup', level: 'P4', topic: 'Heat', theme: 'Energy', marks: 2,
      lo: 'Relate the use of materials to heat conduction (insulators reduce heat loss).',
      question: 'The table shows the temperature of hot water in four cups made of different materials after 15 minutes. Which cup material is best for keeping a drink warm? Explain.',
      table: [{ label: 'Cup A', value: 'Dropped to 70 °C' }, { label: 'Cup B', value: 'Dropped to 52 °C' }, { label: 'Cup C', value: 'Dropped to 61 °C' }, { label: 'Cup D', value: 'Dropped to 45 °C' }],
      choice: "Cup A's material is best for keeping a drink warm.",
      evidence: 'The water in cup A stayed the warmest, at 70 °C (the smallest drop).',
      concept: 'A poor conductor of heat (a good insulator) reduces the loss of heat from the drink.',
      link: 'Because cup A lost the least heat, its material is the best insulator for keeping the drink warm.',
      keywords: ['poor conductor of heat', 'insulator', 'less heat loss'],
      dna: ['cup A is thicker (not stated)', 'cup D because it is coldest'],
    },
    {
      id: 'p4-lid', level: 'P4', topic: 'Heat', theme: 'Energy', marks: 2,
      lo: 'Show an understanding of the expansion of matter when heated.',
      question: 'A metal lid is stuck tightly on a glass jar. After running the metal lid under hot water, it can be unscrewed easily. Explain why.',
      choice: 'The metal lid became easier to unscrew after heating.',
      evidence: 'The metal lid was run under hot water.',
      concept: 'When a metal gains heat, it expands (gets slightly bigger).',
      link: 'The heated metal lid expanded and became slightly looser around the jar, so it could be unscrewed easily.',
      keywords: ['gains heat', 'expands'],
      dna: ['the water made it slippery', 'the glass shrank'],
    },
    /* ---------------- P5 ---------------- */
    {
      id: 'p5-pollination', level: 'P5', topic: 'Reproduction in Plants', theme: 'Cycles', marks: 2,
      lo: 'Understand pollination and the role of insects.',
      question: 'A student counted how many insects visited flowers of four colours over 3 hours. Which flower colour is most effective at attracting insects for pollination? Explain.',
      table: [{ label: 'Red flowers', value: '6 insects' }, { label: 'Yellow flowers', value: '19 insects' }, { label: 'White flowers', value: '11 insects' }, { label: 'Purple flowers', value: '9 insects' }],
      choice: 'The yellow flowers are most effective at attracting insects.',
      evidence: 'The yellow flowers had the most insect visits (19) in the 3 hours.',
      concept: 'Insects carry pollen from flower to flower, so more insect visits means more pollination.',
      link: 'Because yellow flowers attracted the most insects, they are most likely to be pollinated.',
      keywords: ['pollination', 'attract insects', 'transfer pollen'],
      dna: ['yellow is the brightest (not the reason)', 'red flowers'],
      twin: {
        stem: 'Over 2 hours, sweet-smelling flowers were visited by 22 insects while faint-smelling flowers were visited by only 5.',
        ask: 'Which flowers are more effective at attracting insects for pollination? Explain.',
        choice: 'The sweet-smelling flowers are more effective at attracting insects.',
        evidence: 'They were visited by more insects (22 compared with 5) in the same time.',
        concept: 'Insects carry pollen from flower to flower, so more insect visits mean more pollination.',
        link: 'Because the sweet-smelling flowers attracted more insects, they are more likely to be pollinated.',
        keywords: ['pollination', 'attract insects', 'transfer pollen'],
      },
    },
    {
      id: 'p5-seed', level: 'P5', topic: 'Seed Dispersal', theme: 'Cycles', marks: 2,
      lo: 'Recognise methods of seed dispersal and relate them to seed structure.',
      question: 'A seed is very light and has thin, hair-like structures attached to it. State the most likely method of dispersal of this seed and explain your answer.',
      choice: 'The seed is most likely dispersed by wind.',
      evidence: 'The seed is very light and has thin, hair-like structures.',
      concept: 'Light seeds with hair-like or wing-like structures can be carried easily by the wind.',
      link: 'Because the seed is light and its hair-like structures catch the wind, it is dispersed by wind.',
      keywords: ['wind dispersal', 'light', 'carried by the wind'],
      dna: ['dispersed by animals', 'dispersed by water'],
      twin: {
        stem: 'A seed has tiny hooks on its surface that catch onto the fur of passing animals.',
        ask: 'State the most likely method of dispersal of this seed and explain your answer.',
        choice: 'The seed is most likely dispersed by animals.',
        evidence: 'It has tiny hooks that catch onto animal fur.',
        concept: 'Seeds with hooks attach to the fur of passing animals and are carried away.',
        link: 'Because the hooks catch onto fur, the seed is carried away and dispersed by animals.',
        keywords: ['animal dispersal', 'hooks', 'carried by animals'],
      },
    },
    {
      id: 'p5-condensation', level: 'P5', topic: 'Water Cycle', theme: 'Cycles', marks: 2,
      lo: 'Show an understanding of how condensation takes place.',
      question: 'On a hot afternoon, Wei Ming takes a cold canned drink out of the fridge and leaves it on the table. After a few minutes, water droplets form on the outside of the can. Explain how these water droplets formed.',
      choice: 'The water droplets formed by condensation on the can.',
      evidence: 'Water droplets appeared on the cooler outer surface of the cold can.',
      concept: 'Water vapour in the surrounding air loses heat to a cooler surface and condenses into water droplets.',
      link: 'The water vapour in the air came into contact with the cold can, lost heat and condensed into droplets on the can.',
      keywords: ['water vapour', 'loses heat', 'condenses'],
      dna: ['water leaked out of the can', 'the drink seeped through'],
    },
    {
      id: 'p5-evap-fan', level: 'P5', topic: 'Water Cycle', theme: 'Cycles', marks: 2,
      lo: 'Investigate factors affecting the rate of evaporation.',
      question: 'Two identical wet towels were hung up: towel A in front of a fan and towel B with no fan. The table shows their mass after 30 minutes. Does moving air increase the rate of evaporation? Explain using the results.',
      table: [{ label: 'Towel A (with fan)', value: 'Lost 40 g of water' }, { label: 'Towel B (no fan)', value: 'Lost 15 g of water' }],
      choice: 'Yes, moving air increases the rate of evaporation.',
      evidence: 'Towel A, in front of the fan, lost more water (40 g) than towel B (15 g) in the same time.',
      concept: 'Moving air (wind) increases the rate of evaporation of water.',
      link: 'Because the towel in moving air lost water faster, moving air increases the rate of evaporation.',
      keywords: ['rate of evaporation', 'moving air'],
      dna: ['the fan dried it by blowing it away', 'no, they are the same'],
    },
    {
      id: 'p5-respiratory', level: 'P5', topic: 'Respiratory System', theme: 'Systems', marks: 2,
      lo: 'Relate breathing to the supply of oxygen for releasing energy.',
      question: 'When Bala runs in a race, he breathes much faster than when he is resting. Explain why he breathes faster while running.',
      choice: 'Bala breathes faster to take in more oxygen.',
      evidence: 'He is running, which makes his muscles work harder.',
      concept: 'Working muscles need more oxygen to release more energy; the lungs take in oxygen when we breathe.',
      link: 'To supply his muscles with more oxygen to release energy for running, Bala breathes faster.',
      keywords: ['oxygen', 'lungs', 'release energy'],
      dna: ['to take in more air (vague)', 'to breathe out carbon dioxide only'],
      twin: {
        stem: 'When Mei Ling climbs a long flight of stairs, she starts to breathe much faster than when she is standing still.',
        ask: 'Explain why she breathes faster while climbing the stairs.',
        choice: 'Mei Ling breathes faster to take in more oxygen.',
        evidence: 'Climbing the stairs makes her leg muscles work harder.',
        concept: 'Working muscles need more oxygen to release more energy; the lungs take in oxygen when we breathe.',
        link: 'To supply her muscles with more oxygen to release energy for climbing, Mei Ling breathes faster.',
        keywords: ['oxygen', 'lungs', 'release energy'],
      },
    },
    {
      id: 'p5-circulatory', level: 'P5', topic: 'Circulatory System', theme: 'Systems', marks: 2,
      lo: 'Relate the circulatory system to transport of oxygen and digested food.',
      question: 'The table shows the volume of blood flowing to the leg muscles when resting and when jogging. Explain why more blood flows to the leg muscles during jogging.',
      table: [{ label: 'Leg muscles — resting', value: '300 units of blood/min' }, { label: 'Leg muscles — jogging', value: '5700 units of blood/min' }],
      choice: 'More blood flows to the leg muscles during jogging.',
      evidence: 'Blood flow to the leg muscles rose from 300 to 5700 units per minute when jogging.',
      concept: 'Blood carries oxygen and digested food to muscles to release energy; harder-working muscles need more.',
      link: 'Because the jogging leg muscles need more oxygen and digested food to release energy, more blood is pumped to them.',
      keywords: ['oxygen and digested food', 'release energy', 'heart pumps'],
      dna: ['legs get tired', 'blood is thicker when jogging'],
      twin: {
        stem: 'After a large meal, the volume of blood flowing to the stomach and intestines increases.',
        ask: 'Explain why more blood flows to the stomach and intestines after a meal.',
        choice: 'More blood flows to the stomach and intestines after a meal.',
        evidence: 'There is more food to digest and absorb after a large meal.',
        concept: 'Blood transports oxygen and digested food; harder-working organs need more blood supplied to them.',
        link: 'Because the digestive organs are working harder to digest and absorb the food, more blood is pumped to them.',
        keywords: ['oxygen and digested food', 'release energy', 'heart pumps'],
      },
    },
    {
      id: 'p5-circuit', level: 'P5', topic: 'Electrical System', theme: 'Systems', marks: 2,
      lo: 'Understand that current flows only in a closed circuit.',
      question: 'In a simple circuit, the bulb lights up only when the switch is closed, and goes off when the switch is opened. Explain why the bulb lights up only when the switch is closed.',
      diagram: { type: 'circuit', components: ['Battery', 'Bulb', 'Switch'], note: 'Bulb lights only when the switch is closed' },
      choice: 'The bulb lights up only when the switch is closed.',
      evidence: 'The bulb goes off when the switch is opened and lights up when it is closed.',
      concept: 'Electric current can flow only in a closed (complete) circuit.',
      link: 'Closing the switch completes the circuit so current can flow to light the bulb; opening it breaks the circuit.',
      keywords: ['closed circuit', 'electric current flows'],
      dna: ['the switch gives power', 'the battery only works when closed'],
    },
    {
      id: 'p5-conductor', level: 'P5', topic: 'Electrical System', theme: 'Systems', marks: 2,
      lo: 'Identify electrical conductors and insulators.',
      question: 'Different materials were connected one at a time into a circuit with a bulb. The table shows the results. Which material is an electrical conductor? Explain.',
      table: [{ label: 'Copper wire', value: 'Bulb lights up' }, { label: 'Plastic strip', value: 'Bulb does not light' }, { label: 'Rubber band', value: 'Bulb does not light' }, { label: 'Wooden stick', value: 'Bulb does not light' }],
      choice: 'The copper wire is an electrical conductor.',
      evidence: 'The bulb lit up only when the copper wire was connected.',
      concept: 'An electrical conductor allows electric current to flow through it.',
      link: 'Because the bulb lit up with the copper wire, current flowed through it, so copper is a conductor.',
      keywords: ['conductor', 'allows electric current to flow'],
      dna: ['copper is shiny', 'copper is a metal (state it conducts)'],
    },
    {
      id: 'p5-photo-dark', level: 'P5', topic: 'Photosynthesis', theme: 'Energy', marks: 2,
      lo: 'Investigate the requirement of light for photosynthesis.',
      question: "A healthy potted plant is kept in a completely dark cupboard for one week. Explain how being in the dark affects the plant's ability to make food.",
      choice: 'The plant is unable to make food in the dark.',
      evidence: 'The plant received no light in the dark cupboard.',
      concept: 'Plants need light energy to carry out photosynthesis to make food.',
      link: 'Without light energy, the plant cannot carry out photosynthesis, so it cannot make food.',
      keywords: ['light energy', 'photosynthesis', 'make food'],
      dna: ['the plant cannot breathe', 'the plant has no water'],
    },
    {
      id: 'p5-photo-co2', level: 'P5', topic: 'Photosynthesis', theme: 'Energy', marks: 2,
      lo: 'Relate carbon dioxide supply to the rate of photosynthesis.',
      question: 'A water plant was given different amounts of carbon dioxide, and the number of oxygen bubbles produced per minute was counted. What is the relationship between the amount of carbon dioxide and the rate of photosynthesis? Explain using the results.',
      table: [{ label: 'Low carbon dioxide', value: '8 bubbles/min' }, { label: 'Medium carbon dioxide', value: '15 bubbles/min' }, { label: 'High carbon dioxide', value: '24 bubbles/min' }],
      evidence: 'The oxygen bubbles rose from 8 to 15 to 24 per minute as the carbon dioxide increased.',
      concept: 'Carbon dioxide is needed for photosynthesis, so more carbon dioxide gives a faster rate of photosynthesis.',
      link: 'Thus, as the amount of carbon dioxide increases, the rate of photosynthesis increases.',
      keywords: ['carbon dioxide', 'rate of photosynthesis', 'oxygen'],
      dna: ['the plant grew bigger', 'more bubbles means more air'],
      twin: {
        stem: 'A water plant was given more and more light, and the number of oxygen bubbles produced per minute was counted: dim light → 6 bubbles, medium light → 12 bubbles, bright light → 20 bubbles.',
        ask: 'What is the relationship between the amount of light and the rate of photosynthesis? Explain using the results.',
        evidence: 'The oxygen bubbles rose from 6 to 12 to 20 per minute as the light increased.',
        concept: 'Light provides energy for photosynthesis, so more light gives a faster rate of photosynthesis.',
        link: 'Thus, as the amount of light increases, the rate of photosynthesis increases.',
        keywords: ['light', 'rate of photosynthesis', 'oxygen'],
      },
    },
    /* ---------------- P6 ---------------- */
    {
      id: 'p6-elastic-car', level: 'P6', topic: 'Energy Conversion', theme: 'Energy', marks: 2,
      lo: 'Investigate energy conversion from one form to another.',
      question: 'A child winds up the spring of a toy car and lets it go. The car moves quickly across the floor. Describe the main energy conversion that takes place when the car is released.',
      choice: 'Elastic potential energy is converted into kinetic energy.',
      evidence: 'The wound-up spring (storing energy) is released and the car moves.',
      concept: 'A stretched or compressed spring stores elastic potential energy, which converts to kinetic energy of movement.',
      link: "When released, the spring's elastic potential energy is converted into the kinetic energy of the moving car.",
      keywords: ['elastic potential energy', 'kinetic energy'],
      dna: ['potential energy to heat', 'the spring gives power'],
    },
    {
      id: 'p6-gpe', level: 'P6', topic: 'Energy Conversion', theme: 'Energy', marks: 2,
      lo: 'Apply energy conversion to explain how to increase an effect.',
      question: 'In a game, a raised weight is dropped onto a peg to push it into the sand. Suggest one way to push the peg deeper, and explain your answer using energy conversion.',
      choice: 'Raise the weight to a greater height before dropping it.',
      evidence: 'A higher weight has more energy before it is dropped.',
      concept: 'A higher weight has more gravitational potential energy, which converts to more kinetic energy as it falls.',
      link: 'The greater kinetic energy is transferred to the peg, pushing it deeper into the sand.',
      keywords: ['gravitational potential energy', 'kinetic energy', 'transferred'],
      dna: ['drop it faster (you cannot)', 'use a lighter weight'],
    },
    {
      id: 'p6-friction', level: 'P6', topic: 'Forces — Friction', theme: 'Interactions', marks: 2,
      lo: 'Investigate the effect of friction on the motion of objects.',
      question: 'Siti gives the same toy car the same push across four floor surfaces and records how far it travels. Which surface has the most friction? Explain using the results.',
      table: [{ label: 'Carpet', value: '40 cm' }, { label: 'Rubber mat', value: '65 cm' }, { label: 'Wooden floor', value: '110 cm' }, { label: 'Polished tile', value: '150 cm' }],
      choice: 'The carpet has the most friction.',
      evidence: 'The toy car travelled the shortest distance (40 cm) on the carpet.',
      concept: "A greater frictional force opposes the car's motion more, slowing it down faster.",
      link: 'Because more friction stops the car sooner, the shortest distance on the carpet shows it has the most friction.',
      keywords: ['frictional force', 'opposes motion', 'shortest distance'],
      dna: ['the carpet is rough (no link)', 'a choice with no evidence from the table'],
      twin: {
        stem: 'The same ball is rolled with the same push over two surfaces. It travels 30 cm on sand but 200 cm on smooth ice.',
        ask: 'Which surface has more friction? Explain using the results.',
        choice: 'The sand has more friction.',
        evidence: 'The ball travelled a much shorter distance (30 cm) on sand than on ice (200 cm).',
        concept: 'A greater frictional force opposes the motion more, slowing the object down faster.',
        link: 'Because more friction stops the ball sooner, the shorter distance on sand shows it has more friction.',
        keywords: ['frictional force', 'opposes motion', 'shortest distance'],
      },
    },
    {
      id: 'p6-spring', level: 'P6', topic: 'Forces — Elastic Spring', theme: 'Interactions', marks: 2,
      lo: 'Investigate the effect of forces on a spring (extension).',
      question: 'Weights of different sizes are hung from a spring, and the length of the spring is measured. What is the relationship between the weight hung and the extension (stretch) of the spring? Explain using the results.',
      table: [{ label: '100 g weight', value: 'Spring stretched 2 cm' }, { label: '200 g weight', value: 'Spring stretched 4 cm' }, { label: '300 g weight', value: 'Spring stretched 6 cm' }],
      evidence: 'The spring stretched 2 cm, 4 cm then 6 cm as the weight rose from 100 g to 300 g.',
      concept: 'A larger force (heavier weight) pulls the spring more, stretching it further.',
      link: 'Thus, as the weight hung increases, the extension of the spring increases.',
      keywords: ['force', 'extension', 'stretches further'],
      dna: ['the spring gets heavier', 'the spring breaks'],
      twin: {
        stem: 'Loads are hung from an elastic band and its stretch is measured: 1 N → 3 cm, 2 N → 6 cm, 3 N → 9 cm.',
        ask: 'What is the relationship between the load and the stretch of the elastic band? Explain using the results.',
        evidence: 'The band stretched 3 cm, 6 cm then 9 cm as the load rose from 1 N to 3 N.',
        concept: 'A larger force stretches an elastic object more.',
        link: 'Thus, as the load increases, the stretch of the elastic band increases.',
        keywords: ['force', 'extension', 'stretches further'],
      },
    },
    {
      id: 'p6-foodchain', level: 'P6', topic: 'Living Things & Environment', theme: 'Interactions', marks: 2,
      lo: 'Understand the effect of changes in a population within a food chain.',
      question: 'In a food chain, grasshoppers are eaten by frogs. A disease suddenly kills almost all the grasshoppers in an area. Explain what would happen to the population of frogs.',
      diagram: { type: 'chain', nodes: ['Grasshopper', 'Frog'] },
      choice: 'The population of frogs would decrease.',
      evidence: 'Almost all the grasshoppers, which the frogs eat, were killed.',
      concept: 'When a food source is reduced, the animals that feed on it have less food to survive.',
      link: 'With far fewer grasshoppers to eat, many frogs cannot get enough food, so the frog population decreases.',
      keywords: ['food source', 'less food', 'population decreases'],
      dna: ['the frogs die immediately', 'the frog population increases'],
      twin: {
        stem: 'In a food chain, caterpillars are eaten by birds. Hunters remove almost all the birds from an area.',
        ask: 'Explain what would happen to the population of caterpillars.',
        choice: 'The population of caterpillars would increase.',
        evidence: 'Almost all the birds, which eat the caterpillars, were removed.',
        concept: 'When a predator is reduced, fewer of its prey are eaten, so the prey population can grow.',
        link: 'With far fewer birds to eat them, more caterpillars survive, so the caterpillar population increases.',
        keywords: ['predator', 'fewer eaten', 'population increases'],
      },
    },
    {
      id: 'p6-adaptation', level: 'P6', topic: 'Adaptations', theme: 'Interactions', marks: 2,
      lo: 'Recognise that adaptations help organisms survive in their environment.',
      question: 'A polar bear living in a very cold region has a thick layer of fat under its skin. Explain how this thick layer of fat helps the polar bear survive.',
      choice: 'The thick fat helps the polar bear stay warm.',
      evidence: 'The polar bear lives in a very cold region and has a thick layer of fat.',
      concept: 'Fat is a poor conductor of heat, so it reduces the loss of heat from the body to the cold surroundings.',
      link: 'Because the fat reduces heat loss, the polar bear keeps warm and can survive in the cold.',
      keywords: ['poor conductor of heat', 'reduces heat loss', 'keep warm'],
      dna: ['fat keeps the cold out', 'fat stores food only'],
      twin: {
        stem: 'A seal living in cold Arctic waters has a thick layer of blubber (fat) under its skin.',
        ask: 'Explain how this thick layer of blubber helps the seal survive.',
        choice: 'The thick blubber helps the seal stay warm.',
        evidence: 'The seal lives in very cold water and has a thick layer of blubber.',
        concept: 'Fat is a poor conductor of heat, so it reduces the loss of heat from the body to the cold surroundings.',
        link: 'Because the blubber reduces heat loss, the seal keeps warm and can survive in the cold.',
        keywords: ['poor conductor of heat', 'reduces heat loss', 'keep warm'],
      },
    },
  ];

  if (typeof window !== 'undefined') window.SCIENCE_QUESTION_BANK = BANK;
  if (typeof module !== 'undefined' && module.exports) module.exports = BANK;
})();
